*&---------------------------------------------------------------------*
*&  Include           ZCOR_PROJTASK_LABOR_TEMP_SELE
*&---------------------------------------------------------------------*
*======================================================================*
* Selection screen
*======================================================================*
SELECTION-SCREEN: BEGIN OF BLOCK choices WITH FRAME TITLE text-a10.
SELECT-OPTIONS:     date1 FOR coift-endda.
SELECT-OPTIONS: s_bldat FOR covp-bldat.       "++BABAA on 11/29/2023 STSK0070517
SELECTION-SCREEN: END OF BLOCK choices.

SELECTION-SCREEN: BEGIN OF BLOCK charges WITH FRAME TITLE text-a11.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN: BEGIN OF BLOCK a01 WITH FRAME TITLE text-a01.
SELECT-OPTIONS      posnr1  FOR  prps-posid.
SELECTION-SCREEN: END OF BLOCK a01.

SELECTION-SCREEN: BEGIN OF BLOCK s1 WITH FRAME TITLE text-s10.
SELECT-OPTIONS      pernr1  FOR  coift-pernr.
SELECT-OPTIONS      dept1   FOR  coift-skost.
SELECT-OPTIONS      empba   FOR  coift-gsber NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN: END OF BLOCK s1.

SELECTION-SCREEN: BEGIN OF BLOCK s3 WITH FRAME TITLE text-s12.
SELECTION-SCREEN: END OF BLOCK s3.

SELECTION-SCREEN: BEGIN OF BLOCK s2 WITH FRAME TITLE text-s11.
SELECT-OPTIONS      comp    FOR  coift-bukrs DEFAULT '0001' TO '9999'.
SELECT-OPTIONS      gsber   FOR  coift-gsber NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN SKIP.

SELECT-OPTIONS      mgrcc   FOR  coift-skost.
SELECT-OPTIONS      rptcc   FOR  coift-skost.
SELECTION-SCREEN SKIP.

SELECT-OPTIONS      invemp  FOR  prps-cont_invoicer.
SELECT-OPTIONS      anlemp  FOR  prps-yyanlystr.
SELECT-OPTIONS      mgremp  FOR  prps-vernr.

SELECTION-SCREEN: END OF BLOCK s2.

SELECTION-SCREEN: BEGIN OF BLOCK s5 WITH FRAME TITLE text-s14.
SELECTION-SCREEN COMMENT /1(14) text-004.
SELECTION-SCREEN COMMENT 24(3) text-005.
SELECTION-SCREEN COMMENT 30(4) text-006.
SELECTION-SCREEN COMMENT 37(7) text-007.

SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 3(21) text-008.
PARAMETER disc_a RADIOBUTTON GROUP disc DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 30(1) text-xxx.
PARAMETER disc_o RADIOBUTTON GROUP disc.
SELECTION-SCREEN: COMMENT 37(1) text-xxx.
PARAMETER disc_e RADIOBUTTON GROUP disc.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 3(21) text-009.
PARAMETER cbug_a RADIOBUTTON GROUP cbug DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 30(1) text-xxx.
PARAMETER cbug_o RADIOBUTTON GROUP cbug.
SELECTION-SCREEN: COMMENT 37(1) text-xxx.
PARAMETER cbug_e RADIOBUTTON GROUP cbug.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 3(21) text-010.
PARAMETER qre_a RADIOBUTTON GROUP qre DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 30(1) text-xxx.
PARAMETER qre_o RADIOBUTTON GROUP qre.
SELECTION-SCREEN: COMMENT 37(1) text-xxx.
PARAMETER qre_e RADIOBUTTON GROUP qre.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 3(21) text-011.
PARAMETER unbill_a RADIOBUTTON GROUP unb DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 30(1) text-xxx.
PARAMETER unbill_o RADIOBUTTON GROUP unb.
SELECTION-SCREEN: COMMENT 37(1) text-xxx.
PARAMETER unbill_e RADIOBUTTON GROUP unb.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 33(66) text-021.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN ULINE.

SELECT-OPTIONS:    custtyp  FOR  prps-usr02       NO INTERVALS.
SELECT-OPTIONS:    pkgnum   FOR  prps-zps_pkgnum  NO INTERVALS.
SELECT-OPTIONS:    prart    FOR  prps-prart       NO INTERVALS.

SELECTION-SCREEN: END OF BLOCK s5.
SELECTION-SCREEN: END OF BLOCK charges.

SELECTION-SCREEN: BEGIN OF BLOCK s4 WITH FRAME TITLE text-s13.
PARAMETERS:         activ    AS   CHECKBOX   DEFAULT 'X',
                    tecod    AS   CHECKBOX   DEFAULT 'X',
                    closd    AS   CHECKBOX,
                    category AS   CHECKBOX.
SELECTION-SCREEN: END OF BLOCK s4.

SELECTION-SCREEN: BEGIN OF BLOCK fm1 WITH FRAME TITLE text-fm1.
SELECTION-SCREEN:   BEGIN OF LINE.
PARAMETERS:           paging AS CHECKBOX.
SELECTION-SCREEN:     COMMENT 3(40) text-m02 FOR FIELD paging.
SELECTION-SCREEN:   END OF LINE.
SELECTION-SCREEN:   BEGIN OF LINE.
PARAMETERS:           detail AS CHECKBOX.
SELECTION-SCREEN:     COMMENT 3(40) text-m03 FOR FIELD detail.
SELECTION-SCREEN:   END OF LINE.
PARAMETERS:         trans AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN: END OF BLOCK fm1.

SELECTION-SCREEN: BEGIN OF BLOCK rpt2 WITH FRAME TITLE text-srt.
SELECTION-SCREEN:   BEGIN OF LINE.
PARAMETERS            sort1 RADIOBUTTON GROUP sort.
SELECTION-SCREEN:     COMMENT 03(37) text-s01 FOR FIELD sort1.
SELECTION-SCREEN:   END OF LINE.
SELECTION-SCREEN:   BEGIN OF LINE.
PARAMETERS            sort2 RADIOBUTTON GROUP sort.
SELECTION-SCREEN:     COMMENT 03(37) text-s02 FOR FIELD sort2.
SELECTION-SCREEN:   END OF LINE.
SELECTION-SCREEN:   BEGIN OF LINE.
PARAMETERS            sort3 RADIOBUTTON GROUP sort.
SELECTION-SCREEN:     COMMENT 03(37) text-s03 FOR FIELD sort3.
SELECTION-SCREEN:   END OF LINE.
SELECTION-SCREEN: END OF BLOCK rpt2.

SELECTION-SCREEN: BEGIN OF BLOCK rpt3 WITH FRAME TITLE text-003.
PARAMETERS:  expfile LIKE rlgrap-filename NO-DISPLAY.
PARAMETERS:  expdir  LIKE rlgrap-filename.
SELECTION-SCREEN: END OF BLOCK rpt3.

*----------------------------------------------------------------------*
* Report Variant Selection
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-s04.
PARAMETERS: p_vari TYPE slis_vari.
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT (32) text-012 FOR FIELD gcb_alv.
PARAMETERS: gcb_alv AS CHECKBOX.
SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN END OF BLOCK b2.

*----------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK rpt4
                           WITH FRAME TITLE text-001.
PARAMETERS: p_save AS CHECKBOX.
SELECTION-SCREEN: END OF BLOCK rpt4.
